### ISSUE TITLE
Dear author. It doesn't work well.

### ISSUE THREAD

**Issue by vrbvillor** [danielrw7/php-minify-js#1]
I type `http://www.new.com/min/index.php?f=../fisconf.js` in the browser address input. and it outputs nothing. But I echo the $command, it shows `./node_modules/uglify-js/bin/uglifyjs ./../fisconf.js -c`. It's not a usable command in WINDOWS CMD.

Please help me, thanks.

**Comment by postpostscript** [comment]
Hi, thanks for bringing this to my attention. The command should be fixed for Windows now if you pull the latest changes.

If you're still having problems after that, check that:
1. Node.js is installed. The default location for the executable is `C:\nodejs\node.exe` on Windows but you may need to [change that in the script](https://github.com/danielrw7/php-minify-js/blob/master/index.php#L4))
2. apache has read and write permissions for the `cache/` directory

**Comment by postpostscript** [comment]
If this is still isn't working for you then I'll reopen this issue.
